### ISSUE TITLE
The directory could not find the file.

### ISSUE THREAD

**Issue by tiansin** [egodigital/vscode-powertools#1]
![screen shot 2019-01-10 at 13 48 21](https://user-images.githubusercontent.com/4232281/50948749-92d15b80-14de-11e9-88d5-48a848b41e02.png)

I built a file in my home directory and wrote the command code, but I can't load it.

**Comment by ghost** [comment]
@tiansin 

can you post your settings?

**Comment by ghost** [comment]
@tiansin 

I found the issue:

It is

**`~/.vscode-powertools`**
