### ISSUE TITLE
Support button icons?

### ISSUE THREAD

**Issue by borekb** [egodigital/vscode-powertools#12]
Hi, what a great extension! I'm trying to use the Buttons feature and it would be great if I could specify an icon. The [Commands extension](https://github.com/fabiospampinato/vscode-commands) uses something like this:

```
"text": "$(terminal) Show terminal"
```

Any icon from [Octicons](https://octicons.github.com/) can be used there. Do you think this could be supported in Power Tools as well?

**Comment by ghost** [comment]
@borekb 

Thanks :-)

Hmm ... for me, it works.

This is my config:

```json
{
    "ego.power-tools": {
        "buttons": [{
            "action": {
                "script": "myButton.js",
                "type": "script"
            },
            "text": "$(terminal) Show terminal"
        }]
    }
}
````

Can you post your settings here, so we can compare?

**Comment by borekb** [comment]
What, that is supported out of the box? Is that some VSCode thing? I thought it's a feature of that other extension so I didn't even try 😅.

You're right that it just works. Maybe this would be worth mentioning in the wiki?

**Comment by ghost** [comment]
Yes, this is a build-in feature of VSCode.

You can use it, especially in [buttons]() or quick picks (item pickers), e.g.

I have updated the [wiki](https://github.com/egodigital/vscode-powertools/wiki).

**Comment by borekb** [comment]
Awesome! Maybe mention the specific syntax as well on the wiki but at least searching this repo for "icon" now yields a couple of useful results :)

Thank you!

**Comment by ghost** [comment]
Thats right! Done!
