### ISSUE TITLE
How to use VS-Commands for a button?

### ISSUE THREAD

**Issue by mbaas2** [egodigital/vscode-powertools#14]
I see buttons can launch external .js or execute shell-commands, but how about buttons as shortcuts to internal commands, such as `workbench.action.toggleZenMode`)?

**Comment by ghost** [comment]
@mbaas2 

Right, thats also a missing and useful feature! :-)

**Comment by ghost** [comment]
@mbaas2 

The [feature](https://github.com/egodigital/vscode-powertools/wiki/Buttons#visual-studio-code-commands) **is implemented since version 0.36.0**.

**Comment by mbaas2** [comment]
Thanks for the quick implementation! :-)
