### ISSUE TITLE
Deploy Reloaded: Deploy Package - not such option

### ISSUE THREAD

**Issue by tonyhallett** [egodigital/vscode-powertools#15]
I expected the build and compile scripts to be sufficient but build failed complaining about rm even when installed.  I resorted to compile and just copy the res folder across.

**Comment by ghost** [comment]
@tonyhallett 

Have you done the following steps?:

* install [vscode-deploy-reloaded](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded) extenstion
* restart your editor(s)
* open command palette (in Windows and Linux it is `F1`)
* select command `Deploy Reloaded: Deploy ...`
* execute `Package ...` sub command

These steps are optional and only make the copy process of the resources easier.

**Comment by tonyhallett** [comment]
Take it back, my mistake. Keep up the good work 👍

**Comment by tonyhallett** [comment]
rather than installing another extension perhaps a gulp task would be a better option ?

**Comment by ghost** [comment]
@tonyhallett 

That right.

[gulp](https://www.npmjs.com/package/gulp) is a good solution, but on the other hand, another good idea is to realize it with [events](https://github.com/egodigital/vscode-powertools/wiki/Events).
