### ISSUE TITLE
require custom modules

### ISSUE THREAD

**Issue by jacobweber** [egodigital/vscode-powertools#2]
In a custom command, can I "require" my own modules?

I tried something like this in my command script:
```
exports.execute = function (args) {
	console.log(require('./foo'));
};
```

and this in `foo.js`, in the same directory:
```
exports = {
	foo: true
};
```

But it logs an empty object when I run the command.

It **does** seem to be loading the module, since if I change it to an invalid module name, I get a "cannot find module" error instead.

**Comment by mkloubert** [comment]
@jacobweber 

Is the foo.js stored in the .vscode subfolder?

**Comment by jacobweber** [comment]
@mkloubertego No, it's in the same directory as my script. So in this example it's in `/Users/jacobweber/foo.js`:
```
	"ego.power-tools": {
		"commands": {
			"viewvc": {
				"name": "myCommand",
				"script": "/Users/jacobweber/myCommand.js"
			}
		}
	}
```
I'm pretty sure it's finding it, since it gives me an error if I change the name I pass to require().

**Comment by jacobweber** [comment]
I actually had this problem with [vs-script-commands](https://github.com/mkloubert/vs-script-commands) too. Maybe vscode prevents you from importing them somehow?

**Comment by mkloubert** [comment]
@jacobweber 

I resolved the issue. Seems to be a cache problem.

First `myCommand.js` should look like that:

```javascript
exports.execute = function (args) {
    console.log(
        // keep sure that loaded
        // 'foo.js' is NOT from cache
        importModule('./foo')
    );
};

function importModule(modulePath) {
    // remove from cache
    delete require.cache[
        require.resolve(
            modulePath
        )
    ];

    return require(modulePath);
}
```

Then you have to add `module.` before `exports`:

```javascript
module.exports = {
	foo: true
};
```

**Comment by jacobweber** [comment]
Thanks!

**Comment by jacobweber** [comment]
For anyone trying to do this with a module installed in a node_modules folder next to your script, I had to do something like this:

```
const xml2js = require(__dirname + '/node_modules/xml2js');
exports.execute = ...
```
