### ISSUE TITLE
Add support for onWillSaveTextDocument

### ISSUE THREAD

**Issue by StructByLightning** [egodigital/vscode-powertools#24]
Powertools only supports triggering a script when the file is changed or saved. It would be really handy to be able to trigger on the onWillSaveTextDocument event as well.

**Comment by ghost** [comment]
@StructByLightning 

The [file.willsave](https://github.com/egodigital/vscode-powertools/wiki/Events#filewillsave) event is implemented since version 0.41.1.

**Comment by StructByLightning** [comment]
Oh, that's awesome! However, the documentation is partially out of date. Near the top of the page you linked is a table labelled Settings and under Type it says "The type. Current supports: file.changed, file.created, file.deleted and file.saved. Default: all". That's why I thought it wasn't supported.

Thank you for the extension! It's been a huge help.

**Comment by ghost** [comment]
Thanks a lot!

Is fixed.
