### ISSUE TITLE
keyboard shortcuts?

### ISSUE THREAD

**Issue by micahstubbs** [egodigital/vscode-powertools#25]
fantastic plugin, really enjoy the custom button feature. 

I am curious, would you consider keyboard shortcuts in-scope for this plugin? Is there already a VSCode native way to trigger a vscode-powertools script with a keyboard shortcut?

My use case is to have a keyboard shortcut that would trigger the same action as one of my buttons that would be active when I have VSCode open and in focus.

**Comment by ghost** [comment]
@micahstubbs 

You can define a [command](https://github.com/egodigital/vscode-powertools/wiki/Commands) and setup a [key binding](https://code.visualstudio.com/docs/getstarted/keybindings) directly for them.

**Comment by micahstubbs** [comment]
aha, will try this approach. thanks for the guidance on this one!
