### ISSUE TITLE
Move to next space

### ISSUE THREAD

**Issue by robertmarkbram** [egodigital/vscode-powertools#26]
I am trying to use the [previous examples you posted for me](https://github.com/egodigital/vscode-powertools/issues/19), but I couldn't work this out.. the function I am trying is to go to the next space from the cursor position. This is what I have so far.

In my `settings.json` I have:

```javascript
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Go to next space",
                "action": {
                    "type": "script",
                    "script": "C:/Users/robert.bram/AppData/Roaming/Code/User/test_button.js"
                }
            }
        ]
    }
```

In the status bar I now see four "Go to next space" buttons!

![vsCodeButtons](https://user-images.githubusercontent.com/453925/61014134-5a490680-a3c9-11e9-8bae-1febbf28b20f.png)

In the referenced `test_button.js` file I have:

```javascript
exports.execute = async (args) => {
   const vscode  = args.require('vscode');

   goToNextSpace(args);

   vscode.window.showInformationMessage(
       await getClipboardText(args)
   );
}


// go to next space
function goToNextSpace(args) {
   const vscode = args.require('vscode');
   const regEx = /\s/;
   const ACTIVE_EDITOR = vscode.window.activeTextEditor;
   const text = ACTIVE_EDITOR.document.getText();
   const match = regEx.exec(text);
   const nextPos = ACTIVE_EDITOR.document.positionAt(match.index);

   return ACTIVE_EDITOR.document.getText(new vscode.Range(
      nextPos
   ));
}
```

When I press one of the buttons I get:

```
Could not execute button: [Error] 'Invalid arguments'
```

Any ideas?

Rob
:)

**Comment by ghost** [comment]
@robertmarkbram 

I think the problem is, that the constructor of [Range](https://code.visualstudio.com/api/references/vscode-api#Range) class, you would like to use, requires 2 [Position](https://code.visualstudio.com/api/references/vscode-api#Position) objects as arguments, not only one.

**Comment by robertmarkbram** [comment]
Assuming both args would be the same (changing to that location) I have the following. The result: it shows as a dialog whatever I have copied.. but the cursor does not move (and still have the issue where I have multiple buttons).

```
exports.execute = async (args) => {
   const vscode  = args.require('vscode');

   goToNextSpace(args);

   vscode.window.showInformationMessage(
       await getClipboardText(args)
   );
}

// get text from clipboard
async function getClipboardText(args) {
   const vscode = args.require('vscode');

   return await vscode.env.clipboard.readText();
}

// go to next space
function goToNextSpace(args) {
   const vscode = args.require('vscode');
   const regEx = /\s/;
   const ACTIVE_EDITOR = vscode.window.activeTextEditor;
   const text = ACTIVE_EDITOR.document.getText();
   const match = regEx.exec(text);
   const nextPos = ACTIVE_EDITOR.document.positionAt(match.index);

   return ACTIVE_EDITOR.document.getText(new vscode.Range(
      nextPos, nextPos
   ));
}
```

**Comment by ghost** [comment]
@robertmarkbram 

If you want to move the cursor, you have to update the `selection` property in the [TextEditor](https://code.visualstudio.com/api/references/vscode-api#TextEditor) object:

```javascript
ACTIVE_EDITOR.selection = new vscode.Selection(
    /* start line */, /* start column */,

    /* end line */, /* end column */,
);
```

All values start at 0.

You defined the button globally?

**Comment by robertmarkbram** [comment]
Coming back to this. Sorry if this is a zombie post - happy to create a new one if you want.

I saved the script file into the same directory as my global `settings.json`: `C:\Users\Robert Bram\AppData\Roaming\Code\User\test_button.js`

In `C:\Users\Robert Bram\AppData\Roaming\Code\User\settings.json` I have:

```json
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Tests with the editor",
                "action": {
                    "type": "script",
                    "script": "C:/Users/Robert Bram/AppData/Roaming/Code/User/test_button.js"
                }
            }
        ]
    }
```

1. Without putting the absolute path, I kept getting "script not found" errors. I would have expected it to find the script in the same directory just with `"script": "test_button.js"`, but this did not work.
2. As soon as I added the above, I see multiple buttons. Why is that? I am defining the button globally because I want the shortcut to be global.. 
    ![multiple-buttons](https://user-images.githubusercontent.com/453925/87844972-f4f5f280-c905-11ea-8d6c-901d3c4ebf8d.png)
3. Can I assign a keyboard shortcut to launch this instead of a button?
4. Finally, I am still having trouble working out how to change the cursor position to the location of the next space in the file from the cursor. I get how using `new vscode.Selection` can change the position of the cursor

    ```
    // go to start of file
    function gotoStart(args) {
        const vscode = args.require('vscode');

        const ACTIVE_EDITOR = vscode.window.activeTextEditor;
        ACTIVE_EDITOR.selection = new vscode.Selection(
            0, 0,
            0, 0
        );
    }
    ```

    but I am having trouble working out how to find the position of the next space to translate that into the co-ordinates needed for a `new vscode.Selection`. This is what I have so far, but gives me this error: `Could not execute button: [Error] 'Invalid arguments'`

    ```
    // go to next space
    function goToNextSpace(args) {
    
        const vscode = args.require('vscode');
        const regEx = /\s/;

        const ACTIVE_EDITOR = vscode.window.activeTextEditor;
        const text = ACTIVE_EDITOR.document.getText();
        const match = regEx.exec(text);

        const nextPos = ACTIVE_EDITOR.document.positionAt(match.index);

        ACTIVE_EDITOR.selection = new vscode.Selection(
            nextPos.line, nextPos.column,
            nextPos.line, nextPos.column
        );
    }
    ```

Rob
:)

**Comment by robertmarkbram** [comment]
Got this to work as a command.

1. Install [vscode-powertools](https://github.com/egodigital/vscode-powertools)
2. Define powertools commands in settings: `%APPDATA%\Code\User\settings.json`

    ```json
    "ego.power-tools": {
        "commands": {
            "goToNextWhiteSpaceInDocument": {
                // Cannot use environment variables.. yet. https://github.com/microsoft/vscode/issues/2809
                // "script": "${env:APP_DATA}/goToNextWhiteSpaceInDocument.js",
                "script": "[absolute path to APPDATA with forward slashes]/Code/User/goToNextWhiteSpaceInDocument.js",
            },
            "goToPreviousWhiteSpaceInDocument": {
                // Cannot use environment variables.. yet. https://github.com/microsoft/vscode/issues/2809
                // "script": "${env:APP_DATA}/goToPreviousWhiteSpaceInDocument.js",
                "script": "[absolute path to APPDATA with forward slashes]/Code/User/goToPreviousWhiteSpaceInDocument.js",
            }
        }
    }
    ```

3. Copy command files.
    1. Copy [command to go to previous white space](https://github.com/robertmarkbram/VS-Code-Customisations/blob/main/commands/goToPreviousWhiteSpaceInDocument.js) to `%APPDATA%\Code\User\goToPreviousWhiteSpaceInDocument.js`.
    3. Copy [command to go to next white space](https://github.com/robertmarkbram/VS-Code-Customisations/blob/main/commands/goToNextWhiteSpaceInDocument.js) to `%APPDATA%\Code\User\goToNextWhiteSpaceInDocument.js`.
4. Define keyboard shortcuts in `%APPDATA%\Code\User\keybindings.json`

    ```json
    {
        "key": "shift+alt+]",
        "command": "goToNextWhiteSpaceInDocument"
    },
    {
        "key": "shift+alt+[",
        "command": "goToPreviousWhiteSpaceInDocument"
    }
    ```

**Comment by mkloubert** [comment]
@robertmarkbram 

[Values](https://github.com/egodigital/vscode-powertools/wiki/Values#global-values) are not handled the same way as in Visual Studio Code: https://github.com/egodigital/vscode-powertools/wiki/Values#global-values

> Also all environment variables of the current process will be available as (global) values.

Simply try this to include `APP_DATA`:

```jsonc
"ego.power-tools": {
    "commands": {
        "goToNextWhiteSpaceInDocument": {
            // removed the 'env:' prefix ... environment vars are loaded automatically
            "script": "${APP_DATA}/goToNextWhiteSpaceInDocument.js"
        },
        "goToPreviousWhiteSpaceInDocument": {
            // removed the 'env:' prefix ... environment vars are loaded automatically
            "script": "${APP_DATA}/goToPreviousWhiteSpaceInDocument.js"
        }
    }
}
```

**Comment by robertmarkbram** [comment]
What settings file are you putting this in? I don't have a workspace directory. I have a workspace file that describes the multiple folders open in my workspace etc.

**Comment by mkloubert** [comment]
Try [Global settings](https://github.com/egodigital/vscode-powertools/wiki/Global%20Settings).

**Comment by robertmarkbram** [comment]
That's where I had those settings, which is also where environment variables don't work.

%APPDATA%\Code\User\settings.json
