### ISSUE TITLE
Run command as variable

### ISSUE THREAD

**Issue by giantmustache** [egodigital/vscode-powertools#27]
I see the use of these custom commands and I would like to use it in my launch.json as a variable like so `"cd ${command:ego.power-tools.commands.my_command}"`

With a command that actually has a return statement:

    // my_command.js
    exports.execute = async (args) => {
        return "hello"
    };

Would something like that be possible with these power tools?

**Comment by ghost** [comment]
@giantmustache 

You can realize it the following way:

`.vscode/settings.json` (register command `myCommand`, which is executed via `my_command.js`):

```json
{
    "ego.power-tools": {
        "commands": {
            "myCommand": {
                "script": "my_command.js"
            }
        }
    }
}
```

`.vscode/my_command.js` (return a string in `execute()`, which replaces `${command:myCommand}`, s. below):

```javascript
exports.execute = async (args) => {
    return "hello"
};
```

`.vscode/launch.json` (define `${command:myCommand}`, which is replaces by the result of `execute()` from `my_command.js`):

```jsonc
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "myCommand Test",
            "type": "node",
            "request": "launch",
            "args": ["${command:myCommand}"]
        }
    ]
}
```

**Comment by giantmustache** [comment]
This is exactly what I was looking for! Thank you for the fast response.

**Comment by namngo** [comment]
```
Apologize for reopening the issue, but how do I pass an argument into the command?
I've tried this:
"inputs": [
        {
            "id": "blaze_test_target",
            "type": "command",
            "command": "getBlazeTestTarget",
            "args": {
                "baz": "baz1",
                "yoo": "foo",
            }
        },
    ],
```

and I've tried to access the args by 

```
exports.execute = async (args) => {
    return "hello" + args.arguments['baz'];
};
```
I've tried args.baz, args['baz'], args.arguments['baz'], args.arguments.baz... None of them works.
