### ISSUE TITLE
onEvent on.close not working

### ISSUE THREAD

**Issue by ejabu** [egodigital/vscode-powertools#28]
I put this lines of code inside given `my_app.js`

``` javascript
        case 'on.shown':
            // web view has went to the foreground
            vscode.window.showInformationMessage(
                'From WebView: Going to Shown'
            );
            break;

        case 'on.close':
            // the web view is going to be closed
            vscode.window.showInformationMessage(
                'From WebView: Going to Close'
            );
            break;

```
**1. Found Behavior**
I was expecting some information Message by clicking `X` button in file tabs. But I did not see any of it.

Conversely, when I open another Editor and reopen previous Webview, I can see information Message.

**2. Significant use Case**
Later, I will use this mechanicsm to prevent closing Webview conditionally.

**3. Assumptions**
But most likely, `event onclose` cannot be captured in current API.

Is there any workaround ?

I also tried to use this code, but also didnt work

``` javascript
window.onbeforeunload = function(){
    console.log('closing shared worker port...');
    return 'Take care now, bye-bye then.';
  };

```

**Comment by ghost** [comment]
@ejabu 

Unfortunately there is no way in the web view, which is able to send a signal, if it is going to be closed: https://github.com/microsoft/vscode/issues/66842#issuecomment-456208389

**Comment by ghost** [comment]
The event is only fired, if [close()](https://egodigital.github.io/vscode-powertools/api/classes/_apps_.appwebviewbase.html#close) method of [AppWebViewBase](https://egodigital.github.io/vscode-powertools/api/classes/_apps_.appwebviewbase.html) is called, which currently does not happen.

**Comment by ghost** [comment]
@ejabu 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
