### ISSUE TITLE
File explorer and context menus - context menu item name

### ISSUE THREAD

**Issue by PapsOu** [egodigital/vscode-powertools#30]
Hello,

For a custom command related to the file explorer, I've followed this example : https://github.com/egodigital/vscode-powertools/wiki/Commands#file-explorer-and-context-menus

I would like to know if it could be possible to use the name (« Open external » in my example) of the command instead of the too generic label « Execute Power Command » ?

Here the comand config : 
```json
    "ego.power-tools": {
        "commands": {
            "papsou.open-external": {
                "name": "Open external",
                "script": "~/open-in-app.js",
                "forFile": true,
            }
        }
    },
```

```js
// open-in-app.js
exports.execute = function(args) {
    const { exec } = require('child_process')

    if (args.file !== undefined) {
        exec('xdg-open "' + args.file.fsPath + '"')
    }

    return 42
}
```

![20191009-104243](https://user-images.githubusercontent.com/5792207/66465655-93088280-ea81-11e9-9bbc-e83f2a425f60.png)

**Comment by ghost** [comment]
@PapsOu 

Unfortunately not.

Labels of [Visual Studio Code](https://code.visualstudio.com/) context menu entries are hardcoded in the `package.json`: https://github.com/egodigital/vscode-powertools/blob/19f4a30120a63fe2092bfec384f80b77f8c73ddb/package.json#L37

**Comment by PapsOu** [comment]
OK, Is there no way to register the commands in the context menu outside the extension declaration file ?

**Comment by ghost** [comment]
Unfortunately not.

**Comment by PapsOu** [comment]
OK Thanks for your answers !
