### ISSUE TITLE
Possible to "remap"/"conditionalize" close tab - to make files "pinned"/unclosable?

### ISSUE THREAD

**Issue by haakonstorm** [egodigital/vscode-powertools#32]
Would it be possible somehow to use the vscode-powertools to "pin" certain files, so that they won't close with cmd+w (on mac)?

I'm thinking to remap cmd+w to a powertool somehow, and make it call the vscode default close action, but first compare the file path with a simple list of files (`".vscode-pinned-files"`) to see if the files are there. I can make a `safe-to-close.sh` shell script myself, returning zero if the file passed shall be closed and non-zero if not, but I wouldn't know how to get the actual file name within js/vscode/powertools, and code the logic to handle the shell script return status. 

Sorry to put this in the issues section - is there a better place?

This feature is a long standing feature-request in the official vscode forum; implementing it and posting a solution there would make a lot of people happy :)

(I have a huge Home Assistant configuration split to a lot of files, and I'm having a hard time configuring vscode the way I want the config - which files in which split pane, if I close a file I didn't mean to close, upon reopen it opens in the wrong pane, etc. Trying to learn some powertools to mitiagate this! Thanks for a great plugin for vs code.)

**Comment by mkloubert** [comment]
@haakonstorm 

Sorry for the late answer.

No, it is the right place! :-)

I think, I found a solution, which can remap the `CMD + W` (in Windows: `CTRL + W`) key bindings:

It is possible to remap any key binding in Visual Studio Code, even the default ones (https://code.visualstudio.com/docs/getstarted/keybindings).

First add the following section to your global `settings.json` file (https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations):

```json
{
    "ego.power-tools": {
        "commands": {
            "haakonstorm.closeTab": {
                "script": "closeTab.js"
            }
        }
    }
}
```

This will register a [global command](https://code.visualstudio.com/api/extension-guides/command), which executes the script `closeTab.js`, you should create inside the `.vscode-powertools` subfolder of your home directory:

```javascript
exports.execute = async (args) => {
    // s. https://nodejs.org/api/child_process.html
    const child_process = args.require('child_process');
    // s. https://code.visualstudio.com/api/references/vscode-api
    const vscode = args.require('vscode');

    // s. https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options
    const RESULT = child_process.spawnSync('/path/to/your/file/safe-to-close.sh');

    const EXIT_CODE = RESULT.status;
    switch (EXIT_CODE) {
        case 0:
            {
                // close the active editor
                await vscode.commands.executeCommand('workbench.action.closeActiveEditor');
            }
            break;

        default:
            // do something, if failed
            // vscode.window.showErrorMessage('Cannot close tab: ' + EXIT_CODE);
            break;
    }
};
```

Now remap (or reset) all actions, which are binded to `CMD + W` (`CTRL + W`) shortcut, by opening `File >> Preferences >> Keyboard Shortcuts` (`CMD + K` `CMD + S` / `CTRL + K` `CTRL + S`).
In most cases it should be the following ones:

![image](https://user-images.githubusercontent.com/4951215/71708002-4ae1cd80-2dee-11ea-97b9-1014d4dbdb63.png)

Then search for the `haakonstorm.closeTab` command, you defined at the beginning and map it with `CMD + W` (`CTRL + W`).

EDIT: The only problem is, that you are still able to close by "x". There is currently no way to cancel a "close tab" event in the [API of Visual Studio Code](https://code.visualstudio.com/api/references/vscode-api#TextEditor).

**Comment by ghost** [comment]
@haakonstorm 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
