### ISSUE TITLE
toolbar is shown in 1st instance only

### ISSUE THREAD

**Issue by mbaas2** [egodigital/vscode-powertools#34]
Occasionally I run 2 instances of VSC. The pt-toolbar isn't shown in the 2nd instance. I got so used to it that I really miss the added functionality it provides! ;)  Is there any chance to always show it?

**Comment by ghost** [comment]
@mbaas2 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
