### ISSUE TITLE
Re-using modules consumed by PowerTools || "cannot find module"

### ISSUE THREAD

**Issue by Fire-** [egodigital/vscode-powertools#38]
What
-----

Hi friends, 

I'm running into module inclusion issues, as if a module previously imported by PowerTools does not exist or is otherwise not accessible from the current context within a script. 

Example in the [meat](#how) of the post.

Why
-----

I'm looking to create a command to basically "beautify selection" so that I have a quick command to run Beautify against selected javascript text embedded within languages that do not have embedded-language formatting support ( e.g., Haml )

I _may_ simply be going about this the wrong way, but my presumption was along the lines of: 

- PowerTools already includes the `beautify` module to provide utilities such as `$beautify`,
- These scripts are run in the context of PowerTools itself
- I should be able to include/require the module in-kind and utilize the functionality _without_ requiring additional dependencies to be installed, nice!

_**Narrator:** He could not._

How
-----

Given the following command:

```js
"commands": {
  "beautify-selection": {
    "name": "Beautify Selection",
    "description": "Formats the selection using beautify",
    "script": "scripts/format-as-js.js",
    "forFile": true
  }
}
```

And the following script:

```js
// import * as beautify from 'js-beautify'; // "cannot find module 'js-beautify'"

exports.execute = async (args) => {
  const vscode = args.require('vscode');
  const beautify = require('js-beautify').js; // "cannot find module 'js-beautify'"
  const ACTIVE_EDITOR = vscode.window.activeTextEditor;

  activeSelection = ACTIVE_EDITOR.document.getText(ACTIVE_EDITOR.selection.active);

  beautifiedSelection = beautify(activeSelection);

  ACTIVE_EDITOR.edit(builder => {
    builder.insert(
      ACTIVE_EDITOR.selection.active, beautifiedSelection
    );
  });
}
```

The following error is produced:

```
[Error] 'Cannot find module 'js-beautify'
Require stack:
- /Users/fire/projects/.vscode/scripts/format-as-js.js
- /Users/fire/.vscode/extensions/ego-digital.vscode-powertools-0.59.0/out/helpers.js
- /Users/fire/.vscode/extensions/ego-digital.vscode-powertools-0.59.0/out/data.js
- /Users/fire/.vscode/extensions/ego-digital.vscode-powertools-0.59.0/out/commands.js
- /Users/fire/.vscode/extensions/ego-digital.vscode-powertools-0.59.0/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js'
```

Then
-----

If raw dependency reuse actually _isn't_ expected, it would be nice to see `beautify` exposed from PowerTools directly, akin to the other utility libraries noted at the [bottom of the tools page](../wiki/Tools#modules)

<strong><sub><sup><ins>NOTE:</ins></sup></sub></strong> I did look at <code>$beautify</code>, but it opens a new editor window and has no configurable settings, which is undesirable for this use case. It is actually what gave me the idea to try and re-use the existing imports, however.

**Comment by mkloubert** [comment]
@Fire- 

Try to use "args.require('js-beautify')" instead, because the module is part of the extension, but does not seem to be part of your workspace / folder.

**Comment by ghost** [comment]
@Fire- 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
