### ISSUE TITLE
Possible to invoke an external tool to compare two files?

### ISSUE THREAD

**Issue by borekb** [egodigital/vscode-powertools#39]
Hi, I'd like to launch Beyond Compare after I select two files in the explorer. Could Power Tools possibly be used for that?

**Comment by ghost** [comment]
@borekb 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
