### ISSUE TITLE
User, workspace and folder settings override each other

### ISSUE THREAD

**Issue by gbrunow** [egodigital/vscode-powertools#4]
Currently you can set "ego.power-tools" settings at the user preferences, workspace and folder levels, which is great. Folder takes precedence over workspace which takes precedence over user preferences, however, your settings are completed overridden on that order, even if they are not conflicting.

For instance:

- user preferences:

```
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Button 1",
                "action": {
                    "type": "script",
                    "script": "my_button1.js"
                }
            }
        ]
    }
}
```

- workspace:
```
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Button 2",
                "action": {
                    "type": "script",
                    "script": "my_button2.js"
                }
            }
        ]
    }
}
```

- folder:
```
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Button 3",
                "action": {
                    "type": "script",
                    "script": "my_button3.js"
                }
            }
        ]
    }
}
```

Only "Button 3" is rendered.

I'd even argue that it would be totally fine to just show buttons with the same name when they're defined in different levels.

**Comment by ghost** [comment]
@gbrunow 

Yes, that right! The extension only handles the settings, defined in the `resource` scope.

In the next version (in 1 or 2 days - or earlier ;-), we will make it possible to define settings accross all scopes.

**Comment by ghost** [comment]
@gbrunow 

Unfortunately there is no way to merge settings over scopes with the [VSCode API](https://code.visualstudio.com/api/references/vscode-api).

But another way could be to define something like an `imports` setting, which do that manually.

**Comment by gbrunow** [comment]
I imagined this was due to some limitation on the API, I'm guessing when you ask it the settings for `ego.power-tools` you don't receive the whole thing but whatever took precedence.
Would it be possible to have some like `ego.power-tools.user`, `ego.power-tools.workspace` or something like that as the root instead of `ego.power-tools`?

Anyways, keep up with the good work, this is a great extension!

**Comment by ghost** [comment]
@gbrunow 

Yes, this is a good solution.

We try to implement it in the next release (about 2 days), because we will also make things like [commands](https://github.com/egodigital/vscode-powertools/wiki/Commands) and [jobs](https://github.com/egodigital/vscode-powertools/wiki/Jobs) globally available.

**Comment by gbrunow** [comment]
That's awesome!
I was just curious, by the way.

**Comment by ghost** [comment]
@gbrunow 

**Version 0.12.0 has been released.**

Now you can define the following things globally:

* [buttons](https://github.com/egodigital/vscode-powertools/wiki/Buttons)
* [commands](https://github.com/egodigital/vscode-powertools/wiki/Commands)
* [jobs](https://github.com/egodigital/vscode-powertools/wiki/Jobs)
* [placeholders / values](https://github.com/egodigital/vscode-powertools/wiki/Values)

Example:

```json
{
    "ego.power-tools.user": {
        "buttons": [
            {
                "text": "Click me!",
                "tooltip": "You run an awesome script by clicking that button!",
                "action": {
                    "type": "script",
                    "script": "my_button.js"
                }
            }
        ]
    }
}
```

At the [wiki](https://github.com/egodigital/vscode-powertools/wiki/Global%20Settings), there are some more detailed information.

**Comment by gbrunow** [comment]
Awesome! I'll give it a try asap.

**Comment by gbrunow** [comment]
FYI, this was a **breaking change**.
The settings that I had defined in my user settings file under `ego.power-tools` went away, changing it to `ego.power-tools.user` brought them back though.

**Comment by ghost** [comment]
@gbrunow 

Hmm ... I cannot imagin that the behavior of `ego.power-tools` changed, because `ego.power-tools.user` has only be added.

Can you give us an example, what was your old configuration and is now your current one (and where did/do you save it)?

**Comment by gbrunow** [comment]
I guess it was either my mistake or it happened for some other reason, I couldn't reproduce it again.

Sorry about that.
