### ISSUE TITLE
Only run job if a varible in the script has certain value

### ISSUE THREAD

**Issue by Androiderr** [egodigital/vscode-powertools#42]
If my running script has a (processing = 0) then how can i make the job run only when processing is not 0. Thanks in advance.

**Comment by ghost** [comment]
@Androiderr 

Can you show an example, like a config and script?

**Comment by Androiderr** [comment]
*****so this is my setting.js*****
{
    "ego.power-tools": {
        "jobs": [
            {
                "name": "Form job",
                "description": "Form Bot Runs Every 30 seconds.",
                "time": "1 * * * * *",
                "action": {
                    "type": "script",
                    "script": "index.js"
                }
            }
        ]
    }
}
********* This is my index script ***************
var isProcessing = 1;
if(something != anotherthing)
{
isProcessing = 0;
}

**Comment by Androiderr** [comment]
> @Androiderr
> 
> Can you show an example, like a config and script?

I just want to wait for isProcessing to become 0 before the corn job decides to run the script again.

**Comment by g8up** [comment]
Maybe you need a `if` props: https://github.com/egodigital/vscode-powertools/wiki/Jobs#settings

**Comment by ghost** [comment]
@Androiderr 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
