### ISSUE TITLE
How to register commands for all workspaces?

### ISSUE THREAD

**Issue by g8up** [egodigital/vscode-powertools#43]
I have read the wiki-Commnads: https://github.com/egodigital/vscode-powertools/wiki/Commands
As is said , the `my_command.js` should place at `.vscode` subfold of a workspace.

How I can register for all workspaces to share the same command ?

If I regist it in global `settings.json` , which path should I place the script file `my_command.js` ?

**Comment by mkloubert** [comment]
https://github.com/egodigital/vscode-powertools/wiki/Global%20Settings
