### ISSUE TITLE
"IF" condition not working

### ISSUE THREAD

**Issue by Androiderr** [egodigital/vscode-powertools#44]
The cron job is supposed to run every minute and see if the file.txt is present or not. But for some reason, it's not working at all. Please can anyone help? *File name is correct*

{
    "ego.power-tools": {
        "jobs": [
            {
                "name": "Form job",
                "description": "Form Bot Runs Every 60 seconds.",
                "time": "1 * * * * *",
                "autoStart": false,
                "action": {
                    "type": "script",
                    "script": "indeeeeex.js",
                    "if": " !$fs.existsSync( $v['workspaceRoot'] + '/file.txt' ) "
                }
            }
        ]
    }
}

**Comment by ghost** [comment]
@Androiderr 

The [if](https://github.com/egodigital/vscode-powertools/wiki/Conditional%20Settings) checks, only while loading the job entry, if it should be handled or not (or is available).

You should move the check to your script.

For example, for the case your script is in the `.vscode` subfolder of your workspace root:

```javascript
exports.execute = async (args) => {
    const fs = args.require('fs');

    if (!fs.existsSync(__dirname + '/../file.txt') {
        // your logic here
    }
};
```

**Comment by Androiderr** [comment]
> @Androiderr
> 
> The [if](https://github.com/egodigital/vscode-powertools/wiki/Conditional%20Settings) checks, only while loading the job entry, if it should be handled or not (or is available).
> 
> You should move the check to your script.
> 
> For example, for the case your script is in the `.vscode` subfolder of your workspace root:
> 
> ```js
> exports.execute = async (args) => {
>     const fs = args.require('fs');
> 
>     if (!fs.existsSync(__dirname + '/../file.txt') {
>         // your logic here
>     }
> };
> ```

My God you're a genius bro. Such a simple solution and I'm stuck here for 2 days figuring out a method. Thanks :)
