### ISSUE TITLE
It does not work with workspaces

### ISSUE THREAD

**Issue by danielo515** [egodigital/vscode-powertools#46]
I know the title is a bit confusing, but I think it is VSCode fault to use workspaces to refer to two different things. You can understand workspace as the current working directory, and that is fine, but also I can refer to a combination of several directories added to the same workspace that it is then saved to a xxx.workspace file. In this last scenario, it is not possible to define commands for the current workspace, or at least it is not documented how to do.
Even if the workspace is a subset of an actual bigger folder that contains a `.vscode` folder the extension will not be able to find the defined commands.

Not sure if this can be fixed, but I think it was worth mentioning.
Regards

**Comment by ghost** [comment]
@danielo515 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
