### ISSUE TITLE
where to find the ego_log message?

### ISSUE THREAD

**Issue by g8up** [egodigital/vscode-powertools#48]
These days I'm try to handle the usage of power-tools.
It's so great!

I try to create an app, and debug using `vscode.window.showInformationMessage()`.
I wonder other effective debug method.

In this doc
https://github.com/egodigital/vscode-powertools/wiki/Apps#scripting
said `ego_log()`. 

- But where to see the log message ?

- Could you give me some advise ? thx!

- I saw the script generated by `Power Tools: Scripts` - `new script` command, finding `$helpers.GET()` api within.
could it be invoked in `App` ?

**Comment by ghost** [comment]
@g8up 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
