### ISSUE TITLE
what the props of app options

### ISSUE THREAD

**Issue by g8up** [egodigital/vscode-powertools#49]
https://github.com/egodigital/vscode-powertools/wiki/Apps#settings

the props of `options` is unkown.

**Comment by g8up** [comment]
and the `vue` props should be added to the list.

**Comment by mkloubert** [comment]
@g8up 

Thanks! `vue` has a description now.

The `options` setting can be any value and is submitted to each `args.options` property: https://egodigital.github.io/vscode-powertools/api/interfaces/_contracts_.appeventscriptarguments.html#options
