### ISSUE TITLE
Environment variable substitution in script location not working

### ISSUE THREAD

**Issue by RolfNoot** [egodigital/vscode-powertools#51]
I an environment variable on my system:
`$ONETHINX_PACK_LOC` which points to `/Volumes/Data/VScode/GIT/VSCode_OnethinxPack_macOS`

I have a button in my settings along with this script setup:
"script": "${env:ONETHINX_PACK_LOC}/config/scripts/onethinx.js"

When I press the button I get:
Could not execute button: [Error] 'Script '${env:ONETHINX_PACK_LOC}/config/scripts/onethinx.js' not found!'

I also tried to use it like this: `"script": "$ONETHINX_PACK_LOC/config/scripts/onethinx.js"` without reveal.
While hard-coding the location does work:
`"script": "/Volumes/Data/VScode/GIT/VSCode_OnethinxPack_macOSconfig/scripts/onethinx.js"` 

Any ideas?

**Comment by ghost** [comment]
@RolfNoot can you post your complete config?

**Comment by RolfNoot** [comment]
That was fast... Sure!

```
{
  "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
  "C_Cpp.loggingLevel":"Debug",
  "cmake.preferredGenerators": [
    "Unix Makefiles",
    "MinGW Makefiles"
  ],
  "ego.power-tools": {
    "commands": {
      "myCommand": {
          "script": "$ONETHINX_PACK_LOC$/config/scripts/onethinx.js",
          "button": {
              "text": "Click here to start the command."
          }
      }
    },
      "buttons": [
          {
              "text": "Click me!",
              "tooltip": "You run an awesome script by clicking that button!",
              "action": {
                  "type": "script",
                  "script": "$ONETHINX_PACK_LOC$/config/scripts/onethinx.js"
              }
          }
      ]
    }
}
```

**Comment by RolfNoot** [comment]
Running on Mac-OS. This is when I explore the environment variable in terminal:
```
Rolf-Mac-Pro-2:~ rolf$ echo $ONETHINX_PACK_LOC
/Volumes/Data/VScode/GIT/VSCode_OnethinxPack_macOS
```

**Comment by ghost** [comment]
@RolfNoot 

Try use [code based values](https://github.com/egodigital/vscode-powertools/wiki/Values#code):

```javascript
{
  "ego.power-tools": {
    "values": {
      "oneThinxPacLocation": {
        "code": " process.env.ONETHINX_PACK_LOC ",
        "type": "code"
      }
    },
    "commands": {
      "myCommand": {
        "script": "${oneThinxPacLocation}/config/scripts/onethinx.js",
        "button": {
          "text": "Click here to start the command."
        }
      }
    },
    "buttons": [
      {
        "text": "Click me!",
        "tooltip": "You run an awesome script by clicking that button!",
        "action": {
          "type": "script",
          "script": "${oneThinxPacLocation}/config/scripts/onethinx.js"
        }
      }
    ]
  }
}
```

It uses [process.env](https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_env) object.

BTW: Good time to create a value type of `env`, which reads values from environment variables directly. But this is currently a good workarround.

**Comment by RolfNoot** [comment]
That worked, thanks! Will use this workaround for the time-being.

Thanks for the extremely handy extension and the quick support, 5 stars!

**Comment by ghost** [comment]
@RolfNoot 

Oh, I see that the feature is already supported 🙈 : https://github.com/egodigital/vscode-powertools/wiki/Values#global-values (last sentence).

You should be able to simply do (without `env:` prefix, because the extension handles variables its own way, not the VSCode way):

```json
{
  "ego.power-tools": {
    "commands": {
      "myCommand": {
        "script": "${ONETHINX_PACK_LOC}/config/scripts/onethinx.js",
        "button": {
          "text": "Click here to start the command."
        }
      }
    },
    "buttons": [
      {
        "text": "Click me!",
        "tooltip": "You run an awesome script by clicking that button!",
        "action": {
          "type": "script",
          "script": "${ONETHINX_PACK_LOC}/config/scripts/onethinx.js"
        }
      }
    ]
  }
}
```

**Comment by ghost** [comment]
https://github.com/egodigital/vscode-powertools/blob/70f480b41e62fb912104b0d9e093bb0858d4ca85/src/values.ts#L517

**Comment by RolfNoot** [comment]
Thanks, just updated and that worked.

**Comment by RolfNoot** [comment]
Sorry for bothering, but just a small side question (will remove this post). Is it possible to have the big centered messagebox shown (in the editor window, not the small one at the right edge) programatically in the .js function?

**Comment by ghost** [comment]
No problem.

No, the [VSCode API](https://code.visualstudio.com/api/references/vscode-api#window) does not support this.

**Comment by RolfNoot** [comment]
Thanks.

**Comment by ghost** [comment]
Wait: If you want to show it by yourself, you can use `modal` flag in [MessageOptions](https://code.visualstudio.com/api/references/vscode-api#MessageOptions).

**Comment by RolfNoot** [comment]
Worked as well. I'm all set now. Happy with this great extension.

👍
