### ISSUE TITLE
Set cwd for button shell command?

### ISSUE THREAD

**Issue by creage** [egodigital/vscode-powertools#53]
On windows, currently all shell commands are executed in the `C:\Users\me\.vscode-powertools` folder.

How do I force executing a command in the folder of current VSCode session?

```
{
"buttons": [   
    {
        "text": "$(pulse)",
        "action": {
            "type": "shell",          
            "command": "\"powershell.exe\" \"dir\"",
            "silent": false,
            "cwd": "${workspaceRoot}"
        }
    }
]
}
```

returns me
```
Running shell command '"powershell.exe" "dir"' ... [FAILED: '[Error] 'spawn C:\WINDOWS\system32\cmd.exe ENOENT'']
```

**Comment by mkloubert** [comment]
@creage

Can you post an example of your config?

**Comment by ghost** [comment]
@creage 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
