### ISSUE TITLE
Do commands need to run on saved files/folders?

### ISSUE THREAD

**Issue by jacobweber** [egodigital/vscode-powertools#54]
If I have an editor open for an untitled file, and I run "Power Tools: Execute Power Command", it shows me an error like `'/Untitled-1' does not exist!`.

Is it possible to run a command on an un-saved file? My use case is that I want to make some text-processing commands that just operate on the selected text, regardless of whether it's saved in a file.

**Comment by jacobweber** [comment]
It seems like "Power Tools: Commands" works with or without a saved file, so I think that solves my use case. Maybe "Execute Power Command" is only intended to work on files?

**Comment by mkloubert** [comment]
Files and folders.

**Comment by ghost** [comment]
@jacobweber 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
