### ISSUE TITLE
Create new global command command

### ISSUE THREAD

**Issue by danielo515** [egodigital/vscode-powertools#55]
Sorry if the title is not clear. I'm not sure how to better word it.
The request is to add a command that allows you to create a new global command (or button,or script).
If my understanding is correct, you need to edit settings.json, add it there, and then create a file inder the .vscode-powertools home folder. Right?
It would be awesome (and more new users friedly) to have a command taking care of that.

Regards

**Comment by ghost** [comment]
@danielo515 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
