### ISSUE TITLE
Global commands not being shown

### ISSUE THREAD

**Issue by danielo515** [egodigital/vscode-powertools#56]
Hello.
I know that global configs were added not long ago, which is awesome.
But is it possible that global configs are being shadowed by workspace ones? I have defined commands at both levels (using the `.user` suffix) and only the ones at the workspace level works. Here are my configs:

Global:
```
  "ego.power-tools.user": {
    "commands": {
      "graphql-to-flow": {
        "script": "graphql-to-flow.js"
      }
    }
  }
```

Workspace:
```
  "ego.power-tools": {
    "commands": {
      "spring-input": {
        "script": "input-to-spring.js"
      }
    }
  },
```

Content of the ~/.vscode-powertools folder:

```
ls ~/.vscode-powertools
20201215.log       20210128.log       graphql-to-flow.js
```

**Comment by danielo515** [comment]
Just to check I added the same script to the workspace config and it appears, so this is obviously a problem of shadowing of some kind.

**Comment by ghost** [comment]
@danielo515 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
