### ISSUE TITLE
button for call .exe tool

### ISSUE THREAD

**Issue by GiampietroIT** [egodigital/vscode-powertools#57]
Hi,
i just installed the Power Tool.
I would like to create a button to be able to launch an external executable to visual studio code called "MyExe.exe"
I prepared this:

    "ego.power-tools": {
        "buttons": [
            {
                "text": "MyExe 1",
                "tooltip": "MyExe 1 Tool",   
                "executable": "C:\\Software\\Library\\BuildTools\\MyExe.exe" 
            }
        ]
    }

but no it works, could you help me? thank you

**Comment by ghost** [comment]
@GiampietroIT 

Try:

```json
"ego.power-tools": {
    "buttons": [
        {
            "text": "MyExe 1",
            "tooltip": "MyExe 1 Tool",   
            "command": "C:\\Software\\Library\\BuildTools\\MyExe.exe" 
        }
    ]
}
```

You can find more information here: https://github.com/egodigital/vscode-powertools/wiki/Buttons#shell-commands

**Comment by GiampietroIT** [comment]
Hello,
I tried with your suggestion but i get the following error:

![image](https://user-images.githubusercontent.com/66357764/106293155-f78aba80-624d-11eb-81ff-7b4e0879c983.png)

**Comment by ghost** [comment]
Can you try this:

```json
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "MyExe 1",
                "tooltip": "MyExe 1 Tool",
                "action": {
                    "type": "shell",
                    "cwd": "C:\\Software\\Library\\BuildTools",
                    "command": "MyExe.exe"
                }
            }
        ]
    }
}
```

**Comment by GiampietroIT** [comment]
It works!!!! 

Thank you!!
