### ISSUE TITLE
Cannot save to globalStore

### ISSUE THREAD

**Issue by frigierim** [egodigital/vscode-powertools#7]
I am trying to save some state variable from a script, but this is not working:

```
exports.execute = async (args) => {
    await args.globalStore.set("current_platform", "test");
    var platform = args.globalStore.get("current_platform", "test failed");
    log(platform)
}
```

The `platform` variable always reports "test failed"; am I misinterpreting how this works?

**Comment by ghost** [comment]
@frigierim 

this seems to be correct ... can you try the following code (this works for me, when I register a [button](https://github.com/egodigital/vscode-powertools/wiki/Buttons))?:

```javascript
exports.execute = async (args) => {
    const vscode = args.require('vscode');

    await args.globalStore.set("current_platform", "test");
    var platform = args.globalStore.get("current_platform", "test failed");
    
    vscode.window.showInformationMessage(platform);
}
```

In what context do you use your script? Can you post a small example of your settings?

Can you also check the `.store` file in your `${HOME_DIR}/.vscode-powertools` directory?

**Comment by frigierim** [comment]
Thanks for the quick reply!
Your code is not working for me. I am using this when registering my button (in Workspace settings):

```
"ego.power-tools": {
	"commands": 
	{
		"select_platform" : 
		{
			"script": "commands\\ns-commands.js",
			"button": {
					"text": "Change platform",
					"tooltip": "Change build and deploy platform"
			}
		},
	}
}
```
but I still get "Test failed". 
I don't have a ```.vscode-powertools``` directory, but the ```.store``` file is created (empty) in my ```.vscode/commands``` folder (i.e. the folder where the script I am running resides).

Could this layout be the reason for the failure?

**Comment by ghost** [comment]
@frigierim 

Yes, this is a bug ... try to create a `.vscode-powertools` sub folder inside your home directory and it should work.

**Comment by frigierim** [comment]
Lovely, it works!
Thank you.
