### ISSUE TITLE
Changelog View

### ISSUE THREAD

**Issue by RiFi2k** [egodigital/vscode-powertools#8]
Just want to start by saying this could be one of the best ideas for an outside the box extension that exists, I have a million ideas already.

But... could you please make the changelog view logic configurable to be able to be turned off. It's such a small thing and I'm really not trying to nit-pick dumb little things but it probably happened to me 3 or 4 times in the last day as I synced it to my home and work and you pushed an update or whatever. I use an all black theme for VScode and when it was the middle of the night in a dark room it really kind of felt like one of those videos online where you are watching it and the face pops up out of nowhere and screams loudly. That's a complete exaggeration really, but either way even if you ignore this and close it I'll still use your extension and tell everyone I know it's sweet. Just don't update it at night with the lights off.

**Comment by ghost** [comment]
@RiFi2k 

You are already able to turn off the automatic display of the [CHANGELOG](https://github.com/egodigital/vscode-powertools/blob/master/CHANGELOG.md).

Press `F1`, select the command `Power Tools: Global Settings` and turn of the `Open CHANGELOG on startup` checkbox in the `Notifications` tab.

**Comment by RiFi2k** [comment]
Good enough for me, maybe want to document it but other than that thanks for the great extension
