### ISSUE TITLE
On the Make Order,"make all","make clean"....

### ISSUE THREAD

**Issue by 3038922** [egodigital/vscode-powertools#9]
```
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "make clean",
                "tooltip": "clean",
                "action": {
                    "type": "shell",
                    "command": "make clean"
                }
            },
            {
                "text": "make all-j8",
                "tooltip": "rebuild",
                "action": {
                    "type": "shell",
                    "command": "make all -j8"
                }
            }
}
```
I hope the console will display the current compilation information when I click on it.

How can this be achieved?
At present, he only has a box in the lower right corner. I can't see the return information of the console. This command is very common. Hope to have a tutorial.
![image](https://user-images.githubusercontent.com/33926386/52068598-ee5fa800-25b7-11e9-9f46-75248bf18adf.png)

**Comment by ghost** [comment]
@3038922 

Add `silent` to `action` properties and set its values to `(false)`.

```json
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "make clean",
                "tooltip": "clean",
                "action": {
                    "type": "shell",
                    "command": "make clean",
                    "silent": false
                }
            },
            {
                "text": "make all-j8",
                "tooltip": "rebuild",
                "action": {
                    "type": "shell",
                    "command": "make all -j8",
                    "silent": false
                }
            }
    ]
}
```

You should see the result in the output (`CTRL+K CTRL+H`) ... select `Power Tools by e.GO` channel on the right side.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/52070807-a727e600-25bc-11e9-827a-d207807f0f51.png)


thank you.
It would be better if it could be displayed directly on cmd.


At present, I only have a little c/c++. I don't know how to write this kind of code at all.

**Comment by ghost** [comment]
@3038922 

do you mean an update-to-date display of the output?

**Comment by 3038922** [comment]
> @3038922
> 
> do you mean an update-to-date display of the output?

![2](https://user-images.githubusercontent.com/33926386/52071204-7a280300-25bd-11e9-809c-6e75f69ffa15.jpg)


like this.
sorry my english is poor.....
update-to-date display  to terminal .for example:powershell

**Comment by ghost** [comment]
ah, ok ... directly in the terminal ... thanks for the suggestion! :-)
